project:
  type: website
  output-dir: docs

website:
  title: "Abhinag Reddy Machireddy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - blogs.qmd
      - Code.qmd

format:
  html:
    theme: flatly
    css: style.css
    toc: true
    page-layout: full



